language: scala

sudo: required

dist: trusty

git:
  depth: 9999

scala:
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - scripts/travis.sh

install:
  - pip install --user codecov

env:
  global:

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ad8d9cfd5f87cc32760
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
